CmdbNet/Pages/Items/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CmdbNet.Models;
using Microsoft.EntityFrameworkCore;

namespace CmdbNet.Pages.Items
{
    public class CreateModel : PageModel
    {
        private readonly CmdbNet.Models.CmdbNetContext _context;

        public CreateModel(CmdbNet.Models.CmdbNetContext context)
        {
            _context = context;
        }

        public string[] AdNames { get; set; }

        public IActionResult OnGet()
        {
            AdNames = _context.Ad
                    .Select(x => x.Description)
                    .ToArray();

            AdNames = AdNames.Where(x => !string.IsNullOrEmpty(x)).ToArray();

            ViewData["AdID"] = new SelectList(_context.Ad, "AdID", "AdID");
            ViewData["EcmoID"] = new SelectList(_context.Ecmo, "EcmoID", "EcmoID");
            ViewData["EpoID"] = new SelectList(_context.Epo, "EpoID", "EpoID");
            ViewData["SccmID"] = new SelectList(_context.Sccm, "SccmID", "SccmID");
            ViewData["SunflowerID"] = new SelectList(_context.Sunflower, "SunflowerID", "SunflowerID");
            return Page();
        }

        [BindProperty]
        public Cmdb Cmdb { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            string dateString;
            DateTime dateValue;

            string currentUser = HttpContext.User.Identity.Name;
            currentUser = currentUser.Remove(0, 4).Replace('.', ' ');

            if (!ModelState.IsValid)
            {
                return Page();
            }

            dateString = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            dateValue = DateTime.Parse(dateString);

            Cmdb.Modified = dateValue;
            Cmdb.ModifiedBy = currentUser;

            _context.Cmdb.Add(Cmdb);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Index");
        }
    }
}

CmdbNet/Pages/Items/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CmdbNet.Models;

namespace CmdbNet.Pages.Items
{
    public class DeleteModel : PageModel
    {
        private readonly CmdbNet.Models.CmdbNetContext _context;

        public DeleteModel(CmdbNet.Models.CmdbNetContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Cmdb Cmdb { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Cmdb = await _context.Cmdb
                .Include(c => c.AdRecord)
                .Include(c => c.EcmoRecord)
                .Include(c => c.EpoRecord)
                .Include(c => c.SccmRecord)
                .Include(c => c.SunflowerRecord).FirstOrDefaultAsync(m => m.CmdbID == id);

            if (Cmdb == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Cmdb = await _context.Cmdb.FindAsync(id);

            if (Cmdb != null)
            {
                _context.Cmdb.Remove(Cmdb);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }
    }
}

CmdbNet/Pages/Items/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CmdbNet.Models;

namespace CmdbNet.Pages.Items
{
    public class DetailsModel : PageModel
    {
        private readonly CmdbNet.Models.CmdbNetContext _context;

        public DetailsModel(CmdbNet.Models.CmdbNetContext context)
        {
            _context = context;
        }

        public Cmdb Cmdb { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Cmdb = await _context.Cmdb
                .Include(c => c.AdRecord)
                .Include(c => c.EcmoRecord)
                .Include(c => c.EpoRecord)
                .Include(c => c.SccmRecord)
                .Include(c => c.SunflowerRecord).FirstOrDefaultAsync(m => m.CmdbID == id);

            if (Cmdb == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

CmdbNet/Pages/Items/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CmdbNet.Models;
using MimeKit;
using static System.Net.WebRequestMethods;
using MailKit.Net.Smtp;
using System.Text;

namespace CmdbNet.Pages.Items
{
    public class EditModel : PageModel
    {
        private readonly CmdbNet.Models.CmdbNetContext _context;

        public EditModel(CmdbNet.Models.CmdbNetContext context)
        {
            _context = context;
        }

        public string[] AdNames { get; set; }
        public IList<Cmdb> Versions = null;

        [BindProperty]
        public Cmdb Cmdb { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Cmdb = await _context.Cmdb
                .Include(c => c.AdRecord)
                .Include(c => c.EcmoRecord)
                .Include(c => c.EpoRecord)
                .Include(c => c.SccmRecord)
                .Include(c => c.SunflowerRecord).FirstOrDefaultAsync(m => m.CmdbID == id);

            if (Cmdb == null)
            {
                return NotFound();
            }

            AdNames = _context.Ad
                    .Select(x => x.Description)
                    .ToArray();

            AdNames = AdNames.Where(x => !string.IsNullOrEmpty(x)).ToArray();

            ViewData["AdID"] = new SelectList(_context.Ad, "AdID", "AdID");
            ViewData["EcmoID"] = new SelectList(_context.Ecmo, "EcmoID", "EcmoID");
            ViewData["EpoID"] = new SelectList(_context.Epo, "EpoID", "EpoID");
            ViewData["SccmID"] = new SelectList(_context.Sccm, "SccmID", "SccmID");
            ViewData["SunflowerID"] = new SelectList(_context.Sunflower, "SunflowerID", "SunflowerID");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            string dateString;
            DateTime dateValue;

            string currentUser = HttpContext.User.Identity.Name;
            currentUser = currentUser.Remove(0, 4).Replace('.', ' ');

            if (!ModelState.IsValid)
            {
                return Page();
            }

            dateString = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            dateValue = DateTime.Parse(dateString);
            
            Cmdb.Modified = dateValue;
            Cmdb.ModifiedBy = currentUser;

            _context.Attach(Cmdb).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();

                //Send Update Notification Email to Custodian
                if (Cmdb.Custodian != null)
                {
                    var custodian = Cmdb.Custodian;
                    custodian = custodian.Replace(' ', '.') + "@noaa.gov";

                    var message = new MimeMessage();
                    message.From.Add(new MailboxAddress("CMDB\u207A", "saron.desta@noaa.gov"));
                    message.To.Add(new MailboxAddress(Cmdb.Custodian, custodian));
                    message.Subject = "Record Update";
                    var url = "http://ocs-vs-webd1:5000/Items/Details/" + Cmdb.CmdbID;

                    //Find difference between current & previous version
                    

                    var id = Cmdb.CmdbID;
                    
                    Versions = await _context.Cmdb
                        .FromSql($"SELECT TOP 2 * FROM dbo.Cmdb FOR SYSTEM_TIME ALL WHERE CmdbID = {{0}} Order By Modified DESC", id)
                        .AsNoTracking()
                        .ToListAsync();

                    var newVersion = Versions[0];
                    var oldVersion = Versions[1];
                    var pType = oldVersion.GetType();

                    var changes = new StringBuilder();

                    foreach (var property in pType.GetProperties())
                    {
                        if (property.Name.ToLower().Equals("modified") || property.Name.ToLower().Equals("modifiedby"))
                            continue;

                        var oldValue = property.GetValue(oldVersion, null);
                        var newValue = property.GetValue(newVersion, null);

                        if (Equals(oldValue, newValue)) continue;

                        var _oldValue = oldValue == null ? "null" : oldValue.ToString();
                        var _newValue = newValue == null ? "null" : newValue.ToString();

                        changes.Append($"<strong>{property.Name}:</strong> {_oldValue} has changed to {_newValue} <br>");
                        changes.AppendLine();
                    }

                    changes.ToString();


                    message.Body = new TextPart("html")
                    {
                        Text = @"Hello " + Cmdb.Custodian + ",\n " +
                        "<br><br>The following record has been updated in CMDB\u207A by " + Cmdb.ModifiedBy + " on " + Cmdb.Modified + ": \n " +
                        "<br><br><a href=" + url + ">" + Cmdb.CdTag + "</a>" +
                        "<br><br>Changes made:" +
                        "<br><br>" + changes 
                    };

                    using (var emailClient = new SmtpClient())
                    {
                        emailClient.Connect("smtp.gmail.com", 465, true);
                        emailClient.AuthenticationMechanisms.Remove("XOAUTH2");
                        emailClient.Authenticate("saron.desta@noaa.gov", "oqcakjfsobdjkwji");
                        emailClient.Send(message);
                        emailClient.Disconnect(true);
                    }

                }
                
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CmdbExists(Cmdb.CmdbID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("/Index");
        }

        private bool CmdbExists(int id)
        {
            return _context.Cmdb.Any(e => e.CmdbID == id);
        }
    }
}

CmdbNet/Pages/Items/Versions.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CmdbNet.Models;
using System.Data.SqlClient;

namespace CmdbNet.Pages.Items
{
    public class VersionsModel : PageModel
    {
        private readonly CmdbNet.Models.CmdbNetContext _context;

        public VersionsModel(CmdbNet.Models.CmdbNetContext context)
        {
            _context = context;
        }

        public IList<Cmdb> Versions = null;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = id;

            Versions = await _context.Cmdb
                .FromSql($"SELECT * FROM dbo.Cmdb FOR SYSTEM_TIME ALL WHERE CmdbID = {{0}} Order By Modified DESC", item)
                .AsNoTracking()
                .ToListAsync();

            if (Versions == null)
            {
                return NotFound();
            }
            return Page();
        }

        [BindProperty]
        public Cmdb Cmdb { get; set; }

        [HttpPost]
        public async Task<IActionResult> OnPostRestoreVersionAsync(Cmdb item)
        {
            string dateString;
            DateTime dateValue;

            string currentUser = HttpContext.User.Identity.Name;
            currentUser = currentUser.Remove(0, 4).Replace('.', ' ');

            dateString = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            dateValue = DateTime.Parse(dateString);

            Cmdb = item;
            Cmdb.Modified = dateValue;
            Cmdb.ModifiedBy = currentUser;

            _context.Attach(Cmdb).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CmdbExists(Cmdb.CmdbID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("/Index");
        }

        private bool CmdbExists(int id)
        {
            return _context.Cmdb.Any(e => e.CmdbID == id);
        }
    }
}

CmdbNet/Pages/Items/Create.cshtml
@page
@model CmdbNet.Pages.Items.CreateModel

@{
    ViewData["Title"] = "Create";
    ViewData["User"] = HttpContext.User.Identity.Name;
}

<h2>Create</h2>

<h4>Cmdb</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cmdb.CdTag" class="control-label"></label>
                <input asp-for="Cmdb.CdTag" class="form-control" />
                <span asp-validation-for="Cmdb.CdTag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Organization" class="control-label"></label>
                <input asp-for="Cmdb.Organization" class="form-control" />
                <span asp-validation-for="Cmdb.Organization" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.HostName" class="control-label"></label>
                <input asp-for="Cmdb.HostName" class="form-control" />
                <span asp-validation-for="Cmdb.HostName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Location" class="control-label"></label>
                <input asp-for="Cmdb.Location" class="form-control" />
                <span asp-validation-for="Cmdb.Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Floor" class="control-label"></label>
                <input asp-for="Cmdb.Floor" class="form-control" />
                <span asp-validation-for="Cmdb.Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Room" class="control-label"></label>
                <input asp-for="Cmdb.Room" class="form-control" />
                <span asp-validation-for="Cmdb.Room" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.IpAddress" class="control-label"></label>
                <input asp-for="Cmdb.IpAddress" class="form-control" />
                <span asp-validation-for="Cmdb.IpAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.SubnetMask" class="control-label"></label>
                <input asp-for="Cmdb.SubnetMask" class="form-control" />
                <span asp-validation-for="Cmdb.SubnetMask" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.MacAddress" class="control-label"></label>
                <input asp-for="Cmdb.MacAddress" class="form-control" />
                <span asp-validation-for="Cmdb.MacAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Manufacturer" class="control-label"></label>
                <input asp-for="Cmdb.Manufacturer" class="form-control" />
                <span asp-validation-for="Cmdb.Manufacturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Model" class="control-label"></label>
                <input asp-for="Cmdb.Model" class="form-control" />
                <span asp-validation-for="Cmdb.Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.SerialNumber" class="control-label"></label>
                <input asp-for="Cmdb.SerialNumber" class="form-control" />
                <span asp-validation-for="Cmdb.SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.OperatingSystem" class="control-label"></label>
                <input asp-for="Cmdb.OperatingSystem" class="form-control" />
                <span asp-validation-for="Cmdb.OperatingSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.AdUser" class="control-label"></label>
                <input asp-for="Cmdb.AdUser" class="form-control aduser" />
                <span asp-validation-for="Cmdb.AdUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.SunflowerUser" class="control-label"></label>
                <input asp-for="Cmdb.SunflowerUser" class="form-control" />
                <span asp-validation-for="Cmdb.SunflowerUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Status" class="control-label"></label>
                <input asp-for="Cmdb.Status" class="form-control" />
                <span asp-validation-for="Cmdb.Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.ClassType" class="control-label"></label>
                <input asp-for="Cmdb.ClassType" class="form-control" />
                <span asp-validation-for="Cmdb.ClassType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.AcquisitionDate" class="control-label"></label>
                <input asp-for="Cmdb.AcquisitionDate" class="form-control" />
                <span asp-validation-for="Cmdb.AcquisitionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.WarrantyEndDate" class="control-label"></label>
                <input asp-for="Cmdb.WarrantyEndDate" class="form-control" />
                <span asp-validation-for="Cmdb.WarrantyEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Custodian" class="control-label"></label>
                <input asp-for="Cmdb.Custodian" class="form-control aduser" />
                <span asp-validation-for="Cmdb.Custodian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.Comments" class="control-label"></label>
                <input asp-for="Cmdb.Comments" class="form-control" />
                <span asp-validation-for="Cmdb.Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.InventoriedBy" class="control-label"></label>
                <input asp-for="Cmdb.InventoriedBy" class="form-control aduser" />
                <span asp-validation-for="Cmdb.InventoriedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.InventoryDate" class="control-label"></label>
                <input asp-for="Cmdb.InventoryDate" class="form-control" />
                <span asp-validation-for="Cmdb.InventoryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmdb.LastScan" class="control-label"></label>
                <input asp-for="Cmdb.LastScan" class="form-control" />
                <span asp-validation-for="Cmdb.LastScan" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                    <label asp-for="Cmdb.ModifiedBy" class="control-label"></label>
                    <input asp-for="Cmdb.ModifiedBy" class="form-control" />
                    <span asp-validation-for="Cmdb.ModifiedBy" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cmdb.Modified" class="control-label"></label>
                    <input asp-for="Cmdb.Modified" class="form-control" />
                    <span asp-validation-for="Cmdb.Modified" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cmdb.AdID" class="control-label"></label>
                    <select asp-for="Cmdb.AdID" class ="form-control" asp-items="ViewBag.AdID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Cmdb.EcmoID" class="control-label"></label>
                    <select asp-for="Cmdb.EcmoID" class ="form-control" asp-items="ViewBag.EcmoID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Cmdb.EpoID" class="control-label"></label>
                    <select asp-for="Cmdb.EpoID" class ="form-control" asp-items="ViewBag.EpoID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Cmdb.SccmID" class="control-label"></label>
                    <select asp-for="Cmdb.SccmID" class ="form-control" asp-items="ViewBag.SccmID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Cmdb.SunflowerID" class="control-label"></label>
                    <select asp-for="Cmdb.SunflowerID" class ="form-control" asp-items="ViewBag.SunflowerID"></select>
                </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="/Index">Back to List</a>
</div>


@section Scripts {




    <script>
        var list = @Html.Raw(Json.Serialize(Model.AdNames));
        $(".aduser").autocomplete({
            source: list
        });
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

CmdbNet/Pages/Items/Versions.cshtml
@page "{id:int?}"
@model CmdbNet.Pages.Items.VersionsModel

@{
    ViewData["Title"] = "Versions";

    ViewData["User"] = HttpContext.User.Identity.Name;
}

<h2>Versions</h2>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                CdTag
            </th>
            <th>
                Organization
            </th>
            <th>
                HostName
            </th>
            <th>
                Location
            </th>
            <th>
                Floor
            </th>
            <th>
                Room
            </th>
            <th>
                IpAddress
            </th>
            <th>
                SubnetMask
            </th>
            <th>
                MacAddress
            </th>
            <th>
                Manufacturer
            </th>
            <th>
                Model
            </th>
            <th>
                SerialNumber
            </th>
            <th>
                OperatingSystem
            </th>
            <th>
                AdUser
            </th>
            <th>
                SunflowerUser
            </th>
            <th>
                Status
            </th>
            <th>
                ClassType
            </th>
            <th>
                AcquisitionDate
            </th>
            <th>
                WarrantyEndDate
            </th>
            <th>
                Custodian
            </th>
            <th>
                Comments
            </th>
            <th>
                InventoriedBy
            </th>
            <th>
                InventoryDate
            </th>
            <th>
                LastScan
            </th>
            <th>
                ModifiedBy
            </th>
            <th>
                Modified
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Versions)
        {
            <tr>
                <td>
                    <form method="post">
                        <input type="hidden" asp-for="@item.CmdbID" value="@item.CmdbID" />
                        <input type="hidden" asp-for="@item.CdTag" value="@item.CdTag" />
                        <input type="hidden" asp-for="@item.Organization" value="@item.Organization" />
                        <input type="hidden" asp-for="@item.HostName" value="@item.HostName" />
                        <input type="hidden" asp-for="@item.Location" value="@item.Location" />
                        <input type="hidden" asp-for="@item.Floor" value="@item.Floor" />
                        <input type="hidden" asp-for="@item.Room" value="@item.Room" />
                        <input type="hidden" asp-for="@item.IpAddress" value="@item.IpAddress" />
                        <input type="hidden" asp-for="@item.SubnetMask" value="@item.SubnetMask" />
                        <input type="hidden" asp-for="@item.MacAddress" value="@item.MacAddress" />
                        <input type="hidden" asp-for="@item.Manufacturer" value="@item.Manufacturer" />
                        <input type="hidden" asp-for="@item.Model" value="@item.Model" />
                        <input type="hidden" asp-for="@item.SerialNumber" value="@item.SerialNumber" />
                        <input type="hidden" asp-for="@item.OperatingSystem" value="@item.OperatingSystem" />
                        <input type="hidden" asp-for="@item.AdUser" value="@item.AdUser" />
                        <input type="hidden" asp-for="@item.SunflowerUser" value="@item.SunflowerUser" />
                        <input type="hidden" asp-for="@item.Status" value="@item.Status" />
                        <input type="hidden" asp-for="@item.ClassType" value="@item.ClassType" />
                        <input type="hidden" asp-for="@item.AcquisitionDate" value="@item.AcquisitionDate" />
                        <input type="hidden" asp-for="@item.WarrantyEndDate" value="@item.WarrantyEndDate" />
                        <input type="hidden" asp-for="@item.Custodian" value="@item.Custodian" />
                        <input type="hidden" asp-for="@item.Comments" value="@item.Comments" />
                        <input type="hidden" asp-for="@item.InventoriedBy" value="@item.InventoriedBy" />
                        <input type="hidden" asp-for="@item.InventoryDate" value="@item.InventoryDate" />
                        <input type="hidden" asp-for="@item.LastScan" value="@item.LastScan" />
                        <input type="hidden" asp-for="@item.ModifiedBy" value="@item.ModifiedBy" />
                        <input type="hidden" asp-for="@item.Modified" value="@item.Modified" />


                        <button type="submit" class="btn btn-primary" asp-page-handler="RestoreVersion" aria-haspopup="true" aria-expanded="false">
                            Restore
                        </button>
                    </form>
                <td>
                    @item.CdTag
                </td>
                <td>
                    @item.Organization
                </td>
                <td>
                    @item.HostName
                </td>
                <td>
                    @item.Location
                </td>
                <td>
                    @item.Floor
                </td>
                <td>
                    @item.Room
                </td>
                <td>
                    @item.IpAddress
                </td>
                <td>
                    @item.SubnetMask
                </td>
                <td>
                    @item.MacAddress
                </td>
                <td>
                    @item.Manufacturer
                </td>
                <td>
                    @item.Model
                </td>
                <td>
                    @item.SerialNumber
                </td>
                <td>
                    @item.OperatingSystem
                </td>
                <td>
                    @item.AdUser
                </td>
                <td>
                    @item.SunflowerUser
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    @item.ClassType
                </td>
                <td>
                    @item.AcquisitionDate
                </td>
                <td>
                    @item.WarrantyEndDate
                </td>
                <td>
                    @item.Custodian
                </td>
                <td>
                    @item.Comments
                </td>
                <td>
                    @item.InventoriedBy
                </td>
                <td>
                    @item.InventoryDate
                </td>
                <td>
                    @item.LastScan
                </td>
                <td>
                    @item.ModifiedBy
                </td>
                <td>
                    @item.Modified
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-page="./Details" asp-route-id="@Model.Versions[0].CmdbID">Details</a> |
    <a asp-page="/Index">Back to List</a>
</div>